/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mxio_MxIOBuffer */

#ifndef _Included_mxio_MxIOBuffer
#define _Included_mxio_MxIOBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mxio_MxIOBuffer
 * Method:    doGet
 * Signature: ([CILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doGet___3CILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jcharArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doGet
 * Signature: ([SILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doGet___3SILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jshortArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doGet
 * Signature: ([IILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doGet___3IILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jintArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doGet
 * Signature: ([JILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doGet___3JILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jlongArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doGet
 * Signature: ([DILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doGet___3DILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jdoubleArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doGet
 * Signature: ([FILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doGet___3FILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jfloatArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doPut
 * Signature: ([CILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doPut___3CILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jcharArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doPut
 * Signature: ([SILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doPut___3SILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jshortArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doPut
 * Signature: ([IILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doPut___3IILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jintArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doPut
 * Signature: ([JILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doPut___3JILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jlongArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doPut
 * Signature: ([DILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doPut___3DILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jdoubleArray, jint, jobject, jint, jint);

/*
 * Class:     mxio_MxIOBuffer
 * Method:    doPut
 * Signature: ([FILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mxio_MxIOBuffer_doPut___3FILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jfloatArray, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
