/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mxio_JavaMx */

#ifndef _Included_mxio_JavaMx
#define _Included_mxio_JavaMx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mxio_JavaMx
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_mxio_JavaMx_init
  (JNIEnv *, jclass);

/*
 * Class:     mxio_JavaMx
 * Method:    deInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_mxio_JavaMx_deInit
  (JNIEnv *, jclass);

/*
 * Class:     mxio_JavaMx
 * Method:    newEndpoint
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mxio_JavaMx_newEndpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    closeEndpoint
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_closeEndpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    getMyNicId
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_mxio_JavaMx_getMyNicId
  (JNIEnv *, jclass, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    getMyEndpointId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mxio_JavaMx_getMyEndpointId
  (JNIEnv *, jclass, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    getNicId
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mxio_JavaMx_getNicId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     mxio_JavaMx
 * Method:    connect
 * Signature: (IIJII)Z
 */
JNIEXPORT jboolean JNICALL Java_mxio_JavaMx_connect__IIJII
  (JNIEnv *, jclass, jint, jint, jlong, jint, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    connect
 * Signature: (IIJIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_mxio_JavaMx_connect__IIJIIJ
  (JNIEnv *, jclass, jint, jint, jlong, jint, jint, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    disconnect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mxio_JavaMx_disconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    send
 * Signature: (Ljava/nio/ByteBuffer;IIIIIJ)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_send__Ljava_nio_ByteBuffer_2IIIIIJ
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    sendSynchronous
 * Signature: (Ljava/nio/ByteBuffer;IIIIIJ)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_sendSynchronous__Ljava_nio_ByteBuffer_2IIIIIJ
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    send
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIIIJ)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_send__Ljava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2IIIIJ
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jint, jint, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    sendSynchronous
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIIIJ)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_sendSynchronous__Ljava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2IIIIJ
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jint, jint, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    recv
 * Signature: (Ljava/nio/ByteBuffer;IIIIJ)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_recv__Ljava_nio_ByteBuffer_2IIIIJ
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    recv
 * Signature: (Ljava/nio/ByteBuffer;IIIIJJ)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_recv__Ljava_nio_ByteBuffer_2IIIIJJ
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jlong, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    recv
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIIIJ)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_recv__Ljava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2IIIIJ
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    recv
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIIIJJ)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_recv__Ljava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2IIIIJJ
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint, jlong, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    wait
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mxio_JavaMx_wait__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    wait
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_mxio_JavaMx_wait__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    test
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mxio_JavaMx_test
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    iprobe
 * Signature: (IJJ)I
 */
JNIEXPORT jint JNICALL Java_mxio_JavaMx_iprobe
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    probe
 * Signature: (IJJJ)I
 */
JNIEXPORT jint JNICALL Java_mxio_JavaMx_probe
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    cancel
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_mxio_JavaMx_cancel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    forget
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_forget
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    wakeup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mxio_JavaMx_wakeup
  (JNIEnv *, jclass, jint);

/*
 * Class:     mxio_JavaMx
 * Method:    waitForMessage
 * Signature: (IJJJ)J
 */
JNIEXPORT jlong JNICALL Java_mxio_JavaMx_waitForMessage
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    pollForMessage
 * Signature: (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_mxio_JavaMx_pollForMessage
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     mxio_JavaMx
 * Method:    select
 * Signature: (IJJJLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_mxio_JavaMx_select
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
